In [1]:
import torch
import numpy as np

In [2]:
a = torch.Tensor([[0.0867, 0.0868, 0.0883, 0.0868, 0.2082, 0.0867, 0.0867, 0.0956, 0.0871, 0.0870]])
b = torch.Tensor([[0.0876, 0.0877, 0.0888, 0.0883, 0.1925, 0.0876, 0.0875, 0.1010, 0.0908, 0.0882]])

In [3]:
print(a.sum())
print(b.sum())

tensor(0.9999)
tensor(1.)


In [4]:
cos = torch.nn.CosineSimilarity(dim=1)
cos(a, b)

tensor([0.9988])

In [5]:
(a * b).sum(dim=1) / ((a**2).sum(dim=1).sqrt() * (b**2).sum(dim=1).sqrt())

tensor([0.9988])

In [6]:
pdist = torch.nn.PairwiseDistance(p=2)
pdist(a, b)

tensor([0.0172])

In [7]:
pdist(a, a)

tensor([3.1623e-06])

In [8]:
data = torch.Tensor([
    [0.4, 0.3, 0.3],
    [0.36, 0.34, 0.3],
    [0.34, 0.3, 0.36],
])

In [9]:
dist = pdist(data[:1], data)
print(torch.round(dist, decimals=3))
print(torch.abs(dist[0] - dist[-1]))

tensor([0.0000, 0.0570, 0.0850])
tensor(0.0849)


In [10]:
dist = cos(data[:1], data)
print(torch.round(dist, decimals=3))
print(torch.abs(dist[0] - dist[-1]))


tensor([1.0000, 0.9950, 0.9890])
tensor(0.0106)
